// website/src/content/v9/code-snippets/guides/dot-buttons/adding-buttons-solid-01.jsx
import { createSignal, createEffect, on, For } from 'solid-js'
import useEmblaCarousel from 'embla-carousel-solid'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel(() => ({
    loop: false
  }))
  const [scrollSnaps, setScrollSnaps] = createSignal([])

  const goTo = (index) => emblaApi()?.goTo(index)
  const setupSnaps = (emblaApi) => setScrollSnaps(emblaApi.snapList())

  createEffect(
    on(emblaApi, (api) => {
      if (!api) return

      setupSnaps(api)
      api.on('reinit', setupSnaps)
    })
  )

  return (
    <div class="embla">
      <div class="embla__viewport" ref={emblaRef}>
        <div class="embla__container">
          <div class="embla__slide">Slide 1</div>
          <div class="embla__slide">Slide 2</div>
          <div class="embla__slide">Slide 3</div>
        </div>
      </div>

      <div class="embla__dots">
        <For each={scrollSnaps()}>
          {(_, index) => (
            <button class="embla__dot" onClick={() => goTo(index())}>
              {/* Button content */}
            </button>
          )}
        </For>
      </div>
    </div>
  )
}

// website/src/content/v9/code-snippets/guides/dot-buttons/adding-buttons-react-01.jsx
import React, { useState, useEffect } from 'react'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false })
  const [scrollSnaps, setScrollSnaps] = useState([])

  const goTo = (index) => emblaApi?.goTo(index)
  const setupSnaps = (emblaApi) => setScrollSnaps(emblaApi.snapList())

  useEffect(() => {
    if (!emblaApi) return

    setupSnaps(emblaApi)
    emblaApi.on('reinit', setupSnaps)
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>

      <div className="embla__dots">
        {scrollSnaps.map((_, index) => (
          <button
            className="embla__dot"
            key={index}
            onClick={() => goTo(index)}
          >
            {/* Button content */}
          </button>
        ))}
      </div>
    </div>
  )
}
