// website/src/content/v8/code-snippets/api/plugins/adding-event-listeners-svelte-01.svelte
<script>
  import useEmblaCarousel from 'embla-carousel-svelte'
  import Autoplay from 'embla-carousel-autoplay'

  let options = { loop: true }
  let plugins = [Autoplay()]

  const logPluginEvent = (emblaApi, eventName) => {
    console.log(`Autoplay just triggered ${eventName}!`)
  }

  const onInit = (event) => {
    emblaApi = event.detail

    emblaApi.on('autoplay:stop', logPluginEvent)
  }
</script>

<div class="embla">
  <div
    class="embla__viewport"
    on:emblaInit={onInit}
    use:useEmblaCarousel={{ options, plugins }}
  >
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</div>

// website/src/content/v8/code-snippets/api/plugins/adding-event-listeners-react-01.jsx
import React, { useEffect } from 'react'
import useEmblaCarousel from 'embla-carousel-react'
import Autoplay from 'embla-carousel-autoplay'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true }, [Autoplay()])

  const logPluginEvent = (emblaApi, eventName) => {
    console.log(`Autoplay just triggered ${eventName}!`)
  }

  useEffect(() => {
    if (!emblaApi) return

    emblaApi.on('autoplay:stop', logPluginEvent)
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}
