// website/src/content/v8/code-snippets/api/plugins/typescript-plugins-react-01.tsx
// @ts-nocheck
import React, { useState } from 'react'
import { EmblaPluginType } from 'embla-carousel'
import useEmblaCarousel from 'embla-carousel-react'
import Autoplay from 'embla-carousel-autoplay'

export function EmblaCarousel() {
  const [plugins, setPlugins] = useState<EmblaPluginType[]>([Autoplay()])
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true }, plugins)

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}

// website/src/content/v8/code-snippets/api/plugins/typescript-plugins-vue-01.vue
<script setup lang="ts">
// @ts-nocheck
import { ref } from 'vue'
import { EmblaPluginType } from 'embla-carousel'
import useEmblaCarousel from 'embla-carousel-vue'
import Autoplay from 'embla-carousel-autoplay'

const plugins = ref<EmblaPluginType[]>([Autoplay()])
const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true }, plugins)
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>
  </div>
</template>
