// packages/embla-carousel-docs/src/content/code-snippets/api/events/cancelling-events-svelte-01.svelte
<script>
  import useEmblaCarousel from 'embla-carousel-svelte'

  let emblaApi
  let options = { loop: true }
  let allowPointerDownEvent = false

  const onInit = (event) => {
    emblaApi = event.detail

    emblaApi.on('pointerdown', () => {
      return allowPointerDownEvent
    })
  }
</script>

<div class="embla">
  <div
    class="embla__viewport"
    on:emblainit={onInit}
    use:useEmblaCarousel={{ options }}
  >
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</div>

// website/src/content/v9/code-snippets/api/events/cancelling-events-react-01.jsx
import { useEffect, useRef } from 'react'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true })
  let allowPointerDownEvent = useRef(false)

  useEffect(() => {
    if (!emblaApi) return

    emblaApi.on('pointerdown', () => {
      return allowPointerDownEvent.current
    })
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}
