// website/src/content/v9/code-snippets/api/events/cancelling-events-vue-01.vue
<script setup>
import { watch } from 'vue'
import useEmblaCarousel from 'embla-carousel-vue'

const [emblaRef, emblaApi] = useEmblaCarousel()
let allowPointerDownEvent = false

watch(
  emblaApi,
  (api) => {
    if (!api) return

    api.on('pointerdown', () => {
      return allowPointerDownEvent
    })
  },
  { immediate: true }
)
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>
  </div>
</template>

// website/src/content/v9/code-snippets/api/events/cancelling-events-solid-01.jsx
import { createEffect } from 'solid-js'
import useEmblaCarousel from 'embla-carousel-solid'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel(() => ({ loop: true }))
  let allowPointerDownEvent = false

  createEffect(
    () => emblaApi(),
    (api) => {
      if (!api) return

      api.on('pointerdown', () => {
        return allowPointerDownEvent
      })
    }
  )

  return (
    <div class="embla">
      <div class="embla__viewport" ref={emblaRef}>
        <div class="embla__container">
          <div class="embla__slide">Slide 1</div>
          <div class="embla__slide">Slide 2</div>
          <div class="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}
