// website/src/content/v9/code-snippets/api/events/cancelling-events-solid-01.jsx
import { createEffect } from 'solid-js'
import useEmblaCarousel from 'embla-carousel-solid'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel(() => ({ loop: true }))
  let allowPointerDownEvent = false

  createEffect(
    () => emblaApi(),
    (api) => {
      if (!api) return

      api.on('pointerdown', () => {
        return allowPointerDownEvent
      })
    }
  )

  return (
    <div class="embla">
      <div class="embla__viewport" ref={emblaRef}>
        <div class="embla__container">
          <div class="embla__slide">Slide 1</div>
          <div class="embla__slide">Slide 2</div>
          <div class="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}

// website/src/content/v9/code-snippets/api/events/cancelling-events-react-01.jsx
import { useEffect, useRef } from 'react'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true })
  let allowPointerDownEvent = useRef(false)

  useEffect(() => {
    if (!emblaApi) return

    emblaApi.on('pointerdown', () => {
      return allowPointerDownEvent.current
    })
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}
