// website/src/content/v8/code-snippets/api/events/removing-event-listeners-vue-01.vue
<script setup>
import { watch } from 'vue'
import useEmblaCarousel from 'embla-carousel-vue'

const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true })

const logSlidesInViewOnce = (emblaApi, event) => {
  console.log(`${event.type}: ${event.detail.slidesInView}`)
  emblaApi.off('slidesinview', logSlidesInViewOnce)
}

watch(
  emblaApi,
  (api) => {
    if (!api) return
    api.on('slidesinview', logSlidesInViewOnce)
  },
  { immediate: true }
)
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>
  </div>
</template>

// website/src/content/v9/code-snippets/api/events/removing-event-listeners-react-01.jsx
import React, { useEffect } from 'react'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true })

  const logSlidesInViewOnce = (emblaApi, event) => {
    console.log(`${event.type}: ${event.detail.slidesInView}`)
    emblaApi.off('slidesinview', logSlidesInViewOnce)
  }

  useEffect(() => {
    if (!emblaApi) return
    emblaApi.on('slidesinview', logSlidesInViewOnce)
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}
