// website/src/content/v8/code-snippets/guides/required-setup/markup-and-script-vue-01.vue
<script setup>
import useEmblaCarousel from 'embla-carousel-vue'

const [emblaRef] = useEmblaCarousel()
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>

    <!-- Optional: Add navigation controls here -->
  </div>
</template>

// packages/embla-carousel-docs/src/content/code-snippets/guides/required-setup/markup-and-script-svelte-01.svelte
<script>
  import useEmblaCarousel from 'embla-carousel-svelte'
</script>

<div class="embla">
  <div class="embla__viewport" use:useEmblaCarousel>
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>

  <!-- Optional: Add navigation controls here -->
</div>
