// playgrounds/embla-carousel-playground-react/src/Carousel/Carousel.tsx
import { useState, useEffect, useCallback } from 'react'
import { EmblaCarouselType, EmblaOptionsType } from 'embla-carousel'
import useEmblaCarousel from 'embla-carousel-react'
import { DotButton, PrevButton, NextButton } from './Buttons'

type PropType = {
  slides: number[]
  isSsr: boolean
  options?: EmblaOptionsType
}

export const EmblaCarousel = (props: PropType) => {
  const { slides, options, isSsr } = props
  const [refAttached, setRefAttached] = useState(false)
  const [emblaRef, emblaApi, emblaServerApi] = useEmblaCarousel(options)
  const [prevBtnEnabled, setPrevBtnEnabled] = useState(
    emblaServerApi.canGoToPrev()
  )
  const [nextBtnEnabled, setNextBtnEnabled] = useState(
    emblaServerApi.canGoToNext()
  )
  const [selectedIndex, setSelectedIndex] = useState(
    emblaServerApi.selectedSnap()
  )
  const [scrollSnaps, setScrollSnaps] = useState<number[]>([])
  const showSsr = isSsr && !emblaApi

  const scrollPrev = useCallback(
    () => emblaApi && emblaApi.goToPrev(),
    [emblaApi]
  )
  const scrollNext = useCallback(
    () => emblaApi && emblaApi.goToNext(),
    [emblaApi]
  )
  const scrollTo = useCallback(
    (index: number) => emblaApi && emblaApi.goTo(index),
    [emblaApi]
  )

  const onInit = useCallback((emblaApi: EmblaCarouselType) => {
    setScrollSnaps(emblaApi.snapList())
  }, [])

  const onSelect = useCallback((emblaApi: EmblaCarouselType) => {
    setSelectedIndex(emblaApi.selectedSnap())
    setPrevBtnEnabled(emblaApi.canGoToPrev())
    setNextBtnEnabled(emblaApi.canGoToNext())
  }, [])

  useEffect(() => {
    if (!emblaApi) return

    onInit(emblaApi)
    onSelect(emblaApi)

    emblaApi.on('reinit', onInit).on('reinit', onSelect).on('select', onSelect)
  }, [emblaApi, onInit, onSelect])

  useEffect(() => {
    setTimeout(
      () => {
        setRefAttached(true)
      },
      isSsr ? 2000 : 0
    )
  }, [isSsr])

  return (
    <>
      {showSsr && (
        <style id="embla-ssr-styles">
          {emblaServerApi.ssrStyles('.embla__container', '.embla__slide')}
        </style>
      )}

      <div className="playground__ssr-text">
        <strong>SSR:</strong> <span>{showSsr.toString()}</span>
      </div>

      <div className="embla">
        <div
          className="embla__viewport"
          ref={refAttached ? emblaRef : undefined}
        >
          <div className="embla__container">
            {slides.map((index) => (
              <div className="embla__slide" key={index}>
                <div className="embla__slide__number">{index + 1}</div>
              </div>
            ))}
          </div>
        </div>

        <div className="embla__controls">
          <div className="embla__buttons">
            <PrevButton onClick={scrollPrev} enabled={prevBtnEnabled} />
            <NextButton onClick={scrollNext} enabled={nextBtnEnabled} />
          </div>

          <div className="embla__dots">
            {scrollSnaps.map((_, index) => (
              <DotButton
                key={index}
                selected={index === selectedIndex}
                onClick={() => scrollTo(index)}
              />
            ))}
          </div>
        </div>
      </div>
    </>
  )
}

export default EmblaCarousel

// playgrounds/embla-carousel-playground-solid/src/Carousel/Carousel.tsx
import { Component, For, Show, createEffect, createSignal } from 'solid-js'
import { EmblaCarouselType, EmblaOptionsType } from 'embla-carousel'
import useEmblaCarousel from 'embla-carousel-solid'
import { DotButton, NextButton, PrevButton } from './Buttons'

type PropType = {
  slides: number[]
  isSsr: boolean
  options?: EmblaOptionsType
}

export const EmblaCarousel: Component<PropType> = (props) => {
  const [refAttached, setRefAttached] = createSignal(false)
  const [emblaRef, emblaApi, emblaServerApi] = useEmblaCarousel(
    () => props.options
  )
  const [prevBtnEnabled, setPrevBtnEnabled] = createSignal(
    emblaServerApi.canGoToPrev()
  )
  const [nextBtnEnabled, setNextBtnEnabled] = createSignal(
    emblaServerApi.canGoToNext()
  )
  const [selectedIndex, setSelectedIndex] = createSignal(
    emblaServerApi.selectedSnap()
  )
  const [scrollSnaps, setScrollSnaps] = createSignal<number[]>([])
  const [showSsr, setShowSsr] = createSignal(props.isSsr && !emblaApi())

  function scrollPrev(): void {
    emblaApi()?.goToPrev()
  }

  function scrollNext(): void {
    emblaApi()?.goToNext()
  }

  function scrollTo(index: number): void {
    emblaApi()?.goTo(index)
  }

  function onInit(emblaApi: EmblaCarouselType): void {
    setScrollSnaps(emblaApi.snapList())
  }

  function onSelect(emblaApi: EmblaCarouselType): void {
    setSelectedIndex(emblaApi.selectedSnap())
    setPrevBtnEnabled(emblaApi.canGoToPrev())
    setNextBtnEnabled(emblaApi.canGoToNext())
  }

  createEffect(() => {
    const api = emblaApi()
    if (!api) return

    onInit(api)
    onSelect(api)
    api.on('reinit', onInit).on('reinit', onSelect).on('select', onSelect)
  })

  setTimeout(
    () => {
      setRefAttached(true)
      setShowSsr(false)
    },
    props.isSsr ? 2000 : 0
  )

  return (
    <>
      {showSsr() && (
        <style id="embla-ssr-styles">
          {emblaServerApi.ssrStyles('.embla__container', '.embla__slide')}
        </style>
      )}

      <div class="playground__ssr-text">
        <strong>SSR:</strong> <span>{showSsr().toString()}</span>
      </div>

      <div class="embla">
        <Show when={!refAttached()}>
          <div class="embla__viewport">
            <div class="embla__container">
              <For each={props.slides}>
                {(slide) => (
                  <div class="embla__slide">
                    <div class="embla__slide__number">{slide + 1}</div>
                  </div>
                )}
              </For>
            </div>
          </div>
        </Show>

        <Show when={refAttached()}>
          <div class="embla__viewport" ref={emblaRef}>
            <div class="embla__container">
              <For each={props.slides}>
                {(slide) => (
                  <div class="embla__slide">
                    <div class="embla__slide__number">{slide + 1}</div>
                  </div>
                )}
              </For>
            </div>
          </div>
        </Show>

        <div class="embla__controls">
          <div class="embla__buttons">
            <PrevButton onClick={scrollPrev} enabled={prevBtnEnabled()} />
            <NextButton onClick={scrollNext} enabled={nextBtnEnabled()} />
          </div>

          <div class="embla__dots">
            <For each={scrollSnaps()}>
              {(_, index) => {
                return (
                  <DotButton
                    selected={index() === selectedIndex()}
                    onClick={() => scrollTo(index())}
                  />
                )
              }}
            </For>
          </div>
        </div>
      </div>
    </>
  )
}

export default EmblaCarousel
