// packages/embla-carousel-docs/src/content/code-snippets/guides/previous-and-next-buttons/button-placement-svelte-01.svelte
<script>
  import useEmblaCarousel from 'embla-carousel-svelte'

  let options = { loop: false }
</script>

<div class="embla">
  <div class="embla__viewport" use:useEmblaCarousel={{ options }}>
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>

  <!-- Place your previous and next buttons here -->
</div>

// packages/embla-carousel-docs/src/content/code-snippets/guides/previous-and-next-buttons/button-placement-vue-01.vue
<script setup>
import useEmblaCarousel from 'embla-carousel-vue'

const [emblaRef] = useEmblaCarousel({ loop: false })
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>

    <!-- Place your previous and next buttons here -->
  </div>
</template>
