// website/src/content/v9/code-snippets/api/methods/typescript-methods-vue-01.vue
<script setup lang="ts">
import { watch } from 'vue'
import { EmblaCarouselType } from 'embla-carousel'
import useEmblaCarousel from 'embla-carousel-vue'

const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true })

const logSelectedSnap = (emblaApi: EmblaCarouselType) => {
  console.log(emblaApi.selectedSnap())
}

watch(
  emblaApi,
  (api) => {
    if (!api) return
    api.on('select', logSelectedSnap)
  },
  { immediate: true }
)
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>
  </div>
</template>

// website/src/content/v9/code-snippets/api/methods/typescript-methods-react-01.tsx
import React, { useEffect } from 'react'
import { EmblaCarouselType } from 'embla-carousel'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true })

  const logSelectedSnap = (emblaApi: EmblaCarouselType) => {
    console.log(emblaApi.selectedSnap())
  }

  useEffect(() => {
    if (!emblaApi) return
    emblaApi.on('select', logSelectedSnap)
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}
