// website/src/content/v8/code-snippets/guides/previous-and-next-buttons/buttons-state-svelte-01.svelte
<script>
  import useEmblaCarousel from 'embla-carousel-svelte'

  let emblaApi
  let prevButtonDisabled = true
  let nextButtonDisabled = true
  let options = { loop: false }

  const scrollPrev = () => emblaApi?.scrollPrev()
  const scrollNext = () => emblaApi?.scrollNext()

  const toggleButtonsDisabled = (emblaApi) => {
    prevButtonDisabled = !emblaApi.canScrollPrev()
    nextButtonDisabled = !emblaApi.canScrollNext()
  }

  const onInit = (event) => {
    emblaApi = event.detail

    toggleButtonsDisabled(emblaApi)
    emblaApi.on('reInit', toggleButtonsDisabled)
    emblaApi.on('select', toggleButtonsDisabled)
  }
</script>

<div class="embla">
  <div
    class="embla__viewport"
    on:emblaInit={onInit}
    use:useEmblaCarousel={{ options }}
  >
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>

  <button
    class="embla__prev"
    on:click={scrollPrev}
    disabled={prevButtonDisabled}
  >
    Scroll to prev
  </button>
  <button
    class="embla__next"
    on:click={scrollNext}
    disabled={nextButtonDisabled}
  >
    Scroll to next
  </button>
</div>

// website/src/content/v8/code-snippets/guides/previous-and-next-buttons/buttons-state-react-01.jsx
import React, { useState, useEffect } from 'react'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false })
  const [prevButtonDisabled, setPrevButtonDisabled] = useState(true)
  const [nextButtonDisabled, setNextButtonDisabled] = useState(true)

  const scrollPrev = () => emblaApi?.scrollPrev()
  const scrollNext = () => emblaApi?.scrollNext()

  const toggleButtonsDisabled = (emblaApi) => {
    setPrevButtonDisabled(!emblaApi.canScrollPrev())
    setNextButtonDisabled(!emblaApi.canScrollNext())
  }

  useEffect(() => {
    if (!emblaApi) return

    toggleButtonsDisabled(emblaApi)
    emblaApi.on('reInit', toggleButtonsDisabled)
    emblaApi.on('select', toggleButtonsDisabled)
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>

      <button
        className="embla__prev"
        onClick={scrollPrev}
        disabled={prevButtonDisabled}
      >
        Scroll to prev
      </button>
      <button
        className="embla__next"
        onClick={scrollNext}
        disabled={nextButtonDisabled}
      >
        Scroll to next
      </button>
    </div>
  )
}
