// website/src/content/v8/code-snippets/guides/previous-and-next-buttons/buttons-state-react-01.jsx
import React, { useState, useEffect } from 'react'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false })
  const [prevButtonDisabled, setPrevButtonDisabled] = useState(true)
  const [nextButtonDisabled, setNextButtonDisabled] = useState(true)

  const scrollPrev = () => emblaApi?.scrollPrev()
  const scrollNext = () => emblaApi?.scrollNext()

  const toggleButtonsDisabled = (emblaApi) => {
    setPrevButtonDisabled(!emblaApi.canScrollPrev())
    setNextButtonDisabled(!emblaApi.canScrollNext())
  }

  useEffect(() => {
    if (!emblaApi) return

    toggleButtonsDisabled(emblaApi)
    emblaApi.on('reInit', toggleButtonsDisabled)
    emblaApi.on('select', toggleButtonsDisabled)
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>

      <button
        className="embla__prev"
        onClick={scrollPrev}
        disabled={prevButtonDisabled}
      >
        Scroll to prev
      </button>
      <button
        className="embla__next"
        onClick={scrollNext}
        disabled={nextButtonDisabled}
      >
        Scroll to next
      </button>
    </div>
  )
}

// website/src/content/v8/code-snippets/guides/previous-and-next-buttons/buttons-state-vue-01.vue
<script setup>
import { ref, watch } from 'vue'
import useEmblaCarousel from 'embla-carousel-vue'

const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false })
const prevButtonDisabled = ref(true)
const nextButtonDisabled = ref(true)

const scrollPrev = () => emblaApi.value?.scrollPrev()
const scrollNext = () => emblaApi.value?.scrollNext()

const toggleButtonsDisabled = (emblaApi) => {
  prevButtonDisabled.value = !emblaApi.canScrollPrev()
  nextButtonDisabled.value = !emblaApi.canScrollNext()
}

watch(
  emblaApi,
  (api) => {
    if (!api) return

    toggleButtonsDisabled(api)
    api.on('reInit', toggleButtonsDisabled)
    api.on('select', toggleButtonsDisabled)
  },
  { immediate: true }
)
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>

    <button
      class="embla__prev"
      @click="scrollPrev"
      :disabled="prevButtonDisabled"
    >
      Scroll to prev
    </button>
    <button
      class="embla__next"
      @click="scrollNext"
      :disabled="nextButtonDisabled"
    >
      Scroll to next
    </button>
  </div>
</template>
