// packages/embla-carousel-docs/src/content/code-snippets/get-started/solid/adding-plugins-01.jsx
import { createEffect } from 'solid-js'
import createEmblaCarousel from 'embla-carousel-solid'
import Autoplay from 'embla-carousel-autoplay'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = createEmblaCarousel(
    () => ({ loop: true }),
    () => [Autoplay()]
  )

  const scrollToPrev = () => emblaApi()?.scrollToPrev()
  const scrollToNext = () => emblaApi()?.scrollToNext()

  createEffect(() => {
    if (!emblaApi()) return
    emblaApi().plugins().autoplay?.play()
  })

  return (
    <div class="embla">
      <div class="embla__viewport" ref={emblaRef}>
        <div class="embla__container">
          <div class="embla__slide">Slide 1</div>
          <div class="embla__slide">Slide 2</div>
          <div class="embla__slide">Slide 3</div>
        </div>
      </div>

      <button class="embla__prev" onClick={scrollToPrev}>
        Scroll to prev
      </button>
      <button class="embla__next" onClick={scrollToNext}>
        Scroll to next
      </button>
    </div>
  )
}

// packages/embla-carousel-docs/src/content/code-snippets/get-started/react/adding-plugins-01.jsx
import React, { useEffect } from 'react'
import useEmblaCarousel from 'embla-carousel-react'
import Autoplay from 'embla-carousel-autoplay'

export function EmblaCarousel() {
  const [emblaRef] = useEmblaCarousel({ loop: false }, [Autoplay()])

  const scrollToPrev = () => emblaApi?.scrollToPrev()
  const scrollToNext = () => emblaApi?.scrollToNext()

  useEffect(() => {
    if (!emblaApi) return
    emblaApi.plugins().autoplay?.play()
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>

      <button className="embla__prev" onClick={scrollToPrev}>
        Scroll to prev
      </button>
      <button className="embla__next" onClick={scrollToNext}>
        Scroll to next
      </button>
    </div>
  )
}
