// packages/embla-carousel-docs/src/content/code-snippets/guides/server-side-rendering/breakpoints-solid-01.jsx
import { For } from 'solid-js'
import useEmblaCarousel from 'embla-carousel-solid'

export function EmblaCarousel(props) {
  const [emblaRef, emblaApi, emblaServerApi] = useEmblaCarousel(() => ({
    loop: true,
    ssr: props.slides.map(() => 50), // Each slide is 50% of the viewport width
    breakpoints: {
      '(min-width: 768px)': {
        ssr: props.slides.map(() => 70) // Each slide is 70% of the viewport width
      }
    }
  }))

  const renderSsrStyles = () => !emblaApi()

  return (
    <>
      {renderSsrStyles() && (
        <style>
          {emblaServerApi.ssrStyles(`#${props.carouselId}`, '.embla__slide')}
        </style>
      )}

      <div class="embla">
        <div class="embla__viewport" ref={emblaRef}>
          <div class="embla__container" id={props.carouselId}>
            <For each={props.slides}>
              {(slide) => <div class="embla__slide">{slide}</div>}
            </For>
          </div>
        </div>
      </div>
    </>
  )
}

// packages/embla-carousel-docs/src/content/code-snippets/guides/server-side-rendering/breakpoints-svelte-01.svelte
<script>
  import useEmblaCarousel from 'embla-carousel-svelte'

  export let slides
  export let carouselId

  const options = {
    loop: true,
    ssr: slides.map(() => 50), // Each slide is 50% of the viewport width
    breakpoints: {
      '(min-width: 768px)': {
        ssr: slides.map(() => 70) // Each slide is 70% of the viewport width
      }
    }
  }

  let emblaApi
  const emblaServerApi = useEmblaCarousel({ options })

  $: renderSsrStyles = !emblaApi
  const ssrStyles = `
    <style>
      ${emblaServerApi.ssrStyles(`#${carouselId}`, '.embla__slide')}
    </style>
  `

  const onInit = (event) => {
    emblaApi = event.detail
  }
</script>

{#if renderSsrStyles}
  <div>
    {@html ssrStyles}
  </div>
{/if}

<div class="embla">
  <div
    class="embla__viewport"
    use:useEmblaCarousel={{ options }}
    on:emblainit={onInit}
  >
    <div class="embla__container" id={carouselId}>
      {#each slides as slide}
        <div class="embla__slide">{slide}</div>
      {/each}
    </div>
  </div>
</div>
