// website/src/content/v9/code-snippets/guides/grouping-slides/setting-groups-svelte-01.svelte
<script>
  import useEmblaCarousel from 'embla-carousel-svelte'

  let options = { slidesToScroll: 2 }
</script>

<div class="embla">
  <div class="embla__viewport" use:useEmblaCarousel={{ options }}>
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</div>

// website/src/content/v9/code-snippets/guides/grouping-slides/setting-groups-vue-01.vue
<script setup>
import useEmblaCarousel from 'embla-carousel-vue'

const [emblaRef] = useEmblaCarousel({ slidesToScroll: 2 })
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>
  </div>
</template>
