// website/src/content/v9/code-snippets/api/options/changing-options-svelte-01.svelte
<script>
  import useEmblaCarousel from 'embla-carousel-svelte'

  let options = { loop: true }

  const toggleLoop = () => {
    options = {
      ...options,
      loop: !options.loop
    }
  }
</script>

<div class="embla">
  <div class="embla__viewport" use:useEmblaCarousel={{ options }}>
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</div>

// website/src/content/v8/code-snippets/api/options/changing-options-vue-01.vue
<script setup>
import { ref } from 'vue'
import useEmblaCarousel from 'embla-carousel-vue'

const options = ref({ loop: true })
const [emblaRef] = useEmblaCarousel(options)

const toggleLoop = () => {
  options.value = {
    ...options.value,
    loop: !options.value.loop
  }
}
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>
  </div>
</template>
