// packages/embla-carousel-docs/src/content/code-snippets/api/options/changing-options-react-01.jsx
import React, { useState } from 'react'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [options, setOptions] = useState({ loop: true })
  const [emblaRef] = useEmblaCarousel(options)

  const toggleLoop = () => {
    setOptions((currentOptions) => ({
      ...currentOptions,
      loop: !currentOptions.loop
    }))
  }

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}

// website/src/content/v8/code-snippets/api/options/changing-options-solid-01.jsx
import { createSignal } from 'solid-js'
import useEmblaCarousel from 'embla-carousel-solid'

export function EmblaCarousel() {
  const [options, setOptions] = createSignal({ loop: true })
  const [emblaRef] = useEmblaCarousel(() => options())

  const toggleLoop = () => {
    setOptions((currentOptions) => ({
      ...currentOptions,
      loop: !currentOptions.loop
    }))
  }

  return (
    <div class="embla">
      <div class="embla__viewport" ref={emblaRef}>
        <div class="embla__container">
          <div class="embla__slide">Slide 1</div>
          <div class="embla__slide">Slide 2</div>
          <div class="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}
