// packages/embla-carousel-docs/src/content/code-snippets/api/options/global-options-vue-01.vue
<script setup>
import useEmblaCarousel from 'embla-carousel-vue'

useEmblaCarousel.globalOptions = { loop: true }

const [emblaRef] = useEmblaCarousel({ align: 'start' })
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>
  </div>
</template>

// website/src/content/v8/code-snippets/api/options/global-options-react-01.jsx
import React from 'react'
import useEmblaCarousel from 'embla-carousel-react'

useEmblaCarousel.globalOptions = { loop: true }

export function EmblaCarousel() {
  const [emblaRef] = useEmblaCarousel({ align: 'start' })

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}
