// website/src/content/v8/code-snippets/api/options/typescript-options-svelte-01.svelte
<script lang="ts">
// @ts-nocheck
  import { EmblaOptionsType } from 'embla-carousel'
  import useEmblaCarousel from 'embla-carousel-svelte'

  let options: EmblaOptionsType = { loop: true }
</script>

<div class="embla">
  <div class="embla__viewport" use:useEmblaCarousel={{ options }}>
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</div>

// website/src/content/v8/code-snippets/api/options/typescript-options-react-01.tsx
// @ts-nocheck
import React, { useState } from 'react'
import { EmblaOptionsType } from 'embla-carousel'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [options, setOptions] = useState<EmblaOptionsType>({ loop: true })
  const [emblaRef] = useEmblaCarousel(options)

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}
