// playgrounds/embla-carousel-playground-vue/src/Carousel/Carousel.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { EmblaCarouselType, EmblaOptionsType } from 'embla-carousel'
import useEmblaCarousel from 'embla-carousel-vue'
import PrevButton from './PrevButton.vue'
import NextButton from './NextButton.vue'
import DotButton from './DotButton.vue'

const props = defineProps<{
  options: EmblaOptionsType
  slides: number[]
  isSsr: boolean
}>()

const [emblaRef, emblaApi, emblaServerApi] = useEmblaCarousel(props.options)
const refAttached = ref(false)
const prevBtnEnabled = ref(emblaServerApi.canGoToPrev())
const nextBtnEnabled = ref(emblaServerApi.canGoToNext())
const selectedIndex = ref(emblaServerApi.selectedSnap())
const scrollSnaps = ref<number[]>([])
const showSsr = computed(() => props.isSsr && !emblaApi.value)
const ssrStyles = `<style>${emblaServerApi.ssrStyles(
  '.embla__container',
  '.embla__slide'
)}</style>`

function scrollPrev(): void {
  return emblaApi.value?.goToPrev()
}

function scrollNext(): void {
  return emblaApi.value?.goToNext()
}

function scrollTo(index: number): void {
  return emblaApi.value?.goTo(index)
}

function onInit(emblaApi: EmblaCarouselType): void {
  scrollSnaps.value = emblaApi.snapList()
}

function onSelect(emblaApi: EmblaCarouselType): void {
  selectedIndex.value = emblaApi.selectedSnap()
  prevBtnEnabled.value = emblaApi.canGoToPrev()
  nextBtnEnabled.value = emblaApi.canGoToNext()
}

watch(
  () => emblaApi.value,
  () => {
    if (!emblaApi.value) return

    onInit(emblaApi.value)
    onSelect(emblaApi.value)

    emblaApi.value
      .on('reinit', onInit)
      .on('reinit', onSelect)
      .on('select', onSelect)
  },
  { immediate: true }
)

onMounted(() => {
  setTimeout(
    () => {
      refAttached.value = true
    },
    props.isSsr ? 2000 : 0
  )
})
</script>

<template>
  <div v-if="showSsr" v-html="ssrStyles" id="embla-ssr-styles"></div>

  <div class="playground__ssr-text">
    <strong>SSR: </strong>
    <span>{{ showSsr.toString() }}</span>
  </div>

  <div class="embla">
    <div v-if="refAttached" class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div v-for="(_, index) in slides" :key="index" class="embla__slide">
          <div class="embla__slide__number">{{ index + 1 }}</div>
        </div>
      </div>
    </div>

    <div v-else class="embla__viewport">
      <div class="embla__container">
        <div v-for="(_, index) in slides" :key="index" class="embla__slide">
          <div class="embla__slide__number">{{ index + 1 }}</div>
        </div>
      </div>
    </div>

    <div class="embla__controls">
      <div class="embla__buttons">
        <PrevButton @click="scrollPrev" :enabled="prevBtnEnabled" />
        <NextButton @click="scrollNext" :enabled="nextBtnEnabled" />
      </div>

      <div class="embla__dots">
        <DotButton
          v-for="(_, index) in scrollSnaps"
          :key="index"
          :selected="index === selectedIndex"
          @click="scrollTo(index)"
        />
      </div>
    </div>
  </div>
</template>

// playgrounds/embla-carousel-playground-react/src/Carousel/Carousel.tsx
import { useState, useEffect, useCallback } from 'react'
import { EmblaCarouselType, EmblaOptionsType } from 'embla-carousel'
import useEmblaCarousel from 'embla-carousel-react'
import { DotButton, PrevButton, NextButton } from './Buttons'

type PropType = {
  slides: number[]
  isSsr: boolean
  options?: EmblaOptionsType
}

export const EmblaCarousel = (props: PropType) => {
  const { slides, options, isSsr } = props
  const [refAttached, setRefAttached] = useState(false)
  const [emblaRef, emblaApi, emblaServerApi] = useEmblaCarousel(options)
  const [prevBtnEnabled, setPrevBtnEnabled] = useState(
    emblaServerApi.canGoToPrev()
  )
  const [nextBtnEnabled, setNextBtnEnabled] = useState(
    emblaServerApi.canGoToNext()
  )
  const [selectedIndex, setSelectedIndex] = useState(
    emblaServerApi.selectedSnap()
  )
  const [scrollSnaps, setScrollSnaps] = useState<number[]>([])
  const showSsr = isSsr && !emblaApi

  const scrollPrev = useCallback(
    () => emblaApi && emblaApi.goToPrev(),
    [emblaApi]
  )
  const scrollNext = useCallback(
    () => emblaApi && emblaApi.goToNext(),
    [emblaApi]
  )
  const scrollTo = useCallback(
    (index: number) => emblaApi && emblaApi.goTo(index),
    [emblaApi]
  )

  const onInit = useCallback((emblaApi: EmblaCarouselType) => {
    setScrollSnaps(emblaApi.snapList())
  }, [])

  const onSelect = useCallback((emblaApi: EmblaCarouselType) => {
    setSelectedIndex(emblaApi.selectedSnap())
    setPrevBtnEnabled(emblaApi.canGoToPrev())
    setNextBtnEnabled(emblaApi.canGoToNext())
  }, [])

  useEffect(() => {
    if (!emblaApi) return

    onInit(emblaApi)
    onSelect(emblaApi)

    emblaApi.on('reinit', onInit).on('reinit', onSelect).on('select', onSelect)
  }, [emblaApi, onInit, onSelect])

  useEffect(() => {
    setTimeout(
      () => {
        setRefAttached(true)
      },
      isSsr ? 2000 : 0
    )
  }, [isSsr])

  return (
    <>
      {showSsr && (
        <style id="embla-ssr-styles">
          {emblaServerApi.ssrStyles('.embla__container', '.embla__slide')}
        </style>
      )}

      <div className="playground__ssr-text">
        <strong>SSR:</strong> <span>{showSsr.toString()}</span>
      </div>

      <div className="embla">
        <div
          className="embla__viewport"
          ref={refAttached ? emblaRef : undefined}
        >
          <div className="embla__container">
            {slides.map((index) => (
              <div className="embla__slide" key={index}>
                <div className="embla__slide__number">{index + 1}</div>
              </div>
            ))}
          </div>
        </div>

        <div className="embla__controls">
          <div className="embla__buttons">
            <PrevButton onClick={scrollPrev} enabled={prevBtnEnabled} />
            <NextButton onClick={scrollNext} enabled={nextBtnEnabled} />
          </div>

          <div className="embla__dots">
            {scrollSnaps.map((_, index) => (
              <DotButton
                key={index}
                selected={index === selectedIndex}
                onClick={() => scrollTo(index)}
              />
            ))}
          </div>
        </div>
      </div>
    </>
  )
}

export default EmblaCarousel
