// website/src/content/v8/code-snippets/guides/server-side-rendering/setting-up-ssr-react-01.jsx
import React, { useId } from 'react'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel(props) {
  const carouselId = useId()
  const [emblaRef, emblaApi, emblaServerApi] = useEmblaCarousel({
    loop: true,
    ssr: props.slides.map(() => 50) // Each slide is 50% of the viewport width
  })
  const renderSsrStyles = !emblaApi

  return (
    <>
      {renderSsrStyles && (
        <style>
          {emblaServerApi.ssrStyles(`#${carouselId}`, '.embla__slide')}
        </style>
      )}

      <div className="embla">
        <div className="embla__viewport" ref={emblaRef}>
          <div className="embla__container" id={carouselId}>
            {props.slides.map((slide) => (
              <div className="embla__slide" key={slide.id}>
                {slide}
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  )
}

// website/src/content/v8/code-snippets/guides/server-side-rendering/setting-up-ssr-solid-01.jsx
import { For } from 'solid-js'
import useEmblaCarousel from 'embla-carousel-solid'

export function EmblaCarousel(props) {
  const [emblaRef, emblaApi, emblaServerApi] = useEmblaCarousel(() => ({
    loop: true,
    ssr: props.slides.map(() => 50) // Each slide is 50% of the viewport width
  }))

  const renderSsrStyles = () => !emblaApi()

  return (
    <>
      {renderSsrStyles() && (
        <style>
          {emblaServerApi.ssrStyles(`#${props.carouselId}`, '.embla__slide')}
        </style>
      )}

      <div class="embla">
        <div class="embla__viewport" ref={emblaRef}>
          <div class="embla__container" id={props.carouselId}>
            <For each={props.slides}>
              {(slide) => <div class="embla__slide">{slide}</div>}
            </For>
          </div>
        </div>
      </div>
    </>
  )
}
