// website/src/content/v9/code-snippets/api/options/typescript-options-solid-01.tsx
/** @jsxImportSource solid-js */
import { createSignal } from 'solid-js'
import { EmblaOptionsType } from 'embla-carousel'
import useEmblaCarousel from 'embla-carousel-solid'

export function EmblaCarousel() {
  const [options, setOptions] = createSignal<EmblaOptionsType>({ loop: true })
  const [emblaRef] = useEmblaCarousel(options)

  return (
    <div class="embla">
      <div class="embla__viewport" ref={emblaRef}>
        <div class="embla__container">
          <div class="embla__slide">Slide 1</div>
          <div class="embla__slide">Slide 2</div>
          <div class="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}

// website/src/content/v9/code-snippets/api/options/typescript-options-react-01.tsx
import React, { useState } from 'react'
import { EmblaOptionsType } from 'embla-carousel'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [options, setOptions] = useState<EmblaOptionsType>({ loop: true })
  const [emblaRef] = useEmblaCarousel(options)

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}
