// packages/embla-carousel-solid/src/components/useEmblaCarousel.ts
import { Accessor, Setter, createEffect, createSignal } from 'solid-js'
import EmblaCarousel, {
  EmblaCarouselType,
  type EmblaOptionsType,
  type EmblaPluginType
} from 'embla-carousel'
import { areOptionsEqual, arePluginsEqual } from 'embla-carousel-reactive-utils'
import { optionsOrFallback, pluginsOrFallback } from './utils'

export type UseEmblaCarouselType = [
  Setter<HTMLElement | undefined>,
  Accessor<EmblaCarouselType | undefined>,
  EmblaCarouselType
]

function useEmblaCarousel(
  options?: Accessor<EmblaOptionsType | undefined>,
  plugins?: Accessor<EmblaPluginType[] | undefined>
): UseEmblaCarouselType {
  EmblaCarousel.globalOptions = useEmblaCarousel.globalOptions

  let storedOptions = optionsOrFallback(options)
  let storedPlugins = pluginsOrFallback(plugins)

  const serverApi = EmblaCarousel(null, storedOptions, storedPlugins)
  const [clientApi, setClientApi] = createSignal<EmblaCarouselType>()
  const [rootNode, setRootNode] = createSignal<HTMLElement>()

  function reInit(): void {
    const api = clientApi()
    if (api) api.reInit(storedOptions, storedPlugins)
  }

  createEffect(
    () => rootNode(),
    (node) => {
      if (!node) {
        setClientApi(undefined)
        return
      }

      EmblaCarousel.globalOptions = useEmblaCarousel.globalOptions
      const newEmblaApi = EmblaCarousel(node, storedOptions, storedPlugins)
      setClientApi(newEmblaApi)
      return () => newEmblaApi.destroy()
    }
  )

  createEffect(
    () => optionsOrFallback(options),
    (newOptions) => {
      if (areOptionsEqual(storedOptions, newOptions)) return
      storedOptions = newOptions
      reInit()
    }
  )

  createEffect(
    () => pluginsOrFallback(plugins),
    (newPlugins) => {
      if (arePluginsEqual(storedPlugins, newPlugins)) return
      storedPlugins = newPlugins
      reInit()
    }
  )

  return [setRootNode, clientApi, serverApi]
}

declare namespace useEmblaCarousel {
  let globalOptions: EmblaOptionsType | undefined
}

useEmblaCarousel.globalOptions = undefined

export default useEmblaCarousel

// packages/embla-carousel-react/src/components/useEmblaCarousel.ts
import { useRef, useEffect, useState, useCallback } from 'react'
import {
  areOptionsEqual,
  arePluginsEqual,
  canUseDOM
} from 'embla-carousel-reactive-utils'
import EmblaCarousel, {
  EmblaCarouselType,
  EmblaOptionsType,
  EmblaPluginType
} from 'embla-carousel'

export type EmblaViewportRefType = <ViewportElement extends HTMLElement>(
  instance: ViewportElement | null
) => void

export type UseEmblaCarouselType = [
  EmblaViewportRefType,
  EmblaCarouselType | undefined
]

function useEmblaCarousel(
  options: EmblaOptionsType = {},
  plugins: EmblaPluginType[] = []
): UseEmblaCarouselType {
  const storedOptions = useRef(options)
  const storedPlugins = useRef(plugins)
  const [emblaApi, setEmblaApi] = useState<EmblaCarouselType>()
  const [viewport, setViewport] = useState<HTMLElement>()

  const reInit = useCallback(() => {
    if (emblaApi) emblaApi.reInit(storedOptions.current, storedPlugins.current)
  }, [emblaApi])

  useEffect(() => {
    if (areOptionsEqual(storedOptions.current, options)) return
    storedOptions.current = options
    reInit()
  }, [options, reInit])

  useEffect(() => {
    if (arePluginsEqual(storedPlugins.current, plugins)) return
    storedPlugins.current = plugins
    reInit()
  }, [plugins, reInit])

  useEffect(() => {
    if (canUseDOM() && viewport) {
      EmblaCarousel.globalOptions = useEmblaCarousel.globalOptions
      const newEmblaApi = EmblaCarousel(
        viewport,
        storedOptions.current,
        storedPlugins.current
      )
      setEmblaApi(newEmblaApi)
      return () => newEmblaApi.destroy()
    } else {
      setEmblaApi(undefined)
    }
  }, [viewport, setEmblaApi])

  return [<EmblaViewportRefType>setViewport, emblaApi]
}

declare namespace useEmblaCarousel {
  let globalOptions: EmblaOptionsType | undefined
}

useEmblaCarousel.globalOptions = undefined

export default useEmblaCarousel
