// website/src/content/v8/code-snippets/guides/slide-gaps/in-view-configuration-react-01.jsx
import React, { useEffect } from 'react'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({
    inViewMargin: '0px -20px 0px 0px'
  })

  const logSlidesInView = (emblaApi, event) => {
    console.log('Slides entered view: ' + event.detail.slidesEnterView)
  }

  useEffect(() => {
    if (!emblaApi) return
    emblaApi.on('slidesinview', logSlidesInView)
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}

// packages/embla-carousel-docs/src/content/code-snippets/guides/slide-gaps/in-view-configuration-svelte-01.svelte
<script>
  import useEmblaCarousel from 'embla-carousel-svelte'

  let emblaApi
  let options = { inViewMargin: '0px -20px 0px 0px' }

  const logSlidesInView = (emblaApi, event) => {
    console.log('Slides entered view: ' + event.detail.slidesEnterView)
  }

  const onInit = (event) => {
    emblaApi = event.detail
    emblaApi.on('slidesinview', logSlidesInView)
  }
</script>

<div class="embla">
  <div
    class="embla__viewport"
    on:emblainit={onInit}
    use:useEmblaCarousel={{ options }}
  >
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</div>
