// website/src/content/v8/code-snippets/api/options/global-options-svelte-01.svelte
<script>
  import useEmblaCarousel from 'embla-carousel-svelte'

  useEmblaCarousel.globalOptions = { loop: true }

  let options = { align: 'start' }
</script>

<div class="embla">
  <div class="embla__viewport" use:useEmblaCarousel={{ options }}>
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</div>

// packages/embla-carousel-docs/src/content/code-snippets/api/options/global-options-vue-01.vue
<script setup>
import useEmblaCarousel from 'embla-carousel-vue'

useEmblaCarousel.globalOptions = { loop: true }

const [emblaRef] = useEmblaCarousel({ align: 'start' })
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>
  </div>
</template>
