// website/src/content/v8/code-snippets/api/plugins/adding-event-listeners-vue-01.vue
<script setup>
import { watch } from 'vue'
import useEmblaCarousel from 'embla-carousel-vue'
import Autoplay from 'embla-carousel-autoplay'

const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true }, [Autoplay()])

const logAutoplayStart = (emblaApi, event) => {
  console.log(`${event.type} fired`)
}

watch(
  emblaApi,
  (api) => {
    if (!api) return

    api.on('autoplay:play', logAutoplayStart)
    api.plugins().autoplay?.play()
  },
  { immediate: true }
)
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>
  </div>
</template>

// packages/embla-carousel-docs/src/content/code-snippets/api/plugins/adding-event-listeners-react-01.jsx
import React, { useEffect } from 'react'
import useEmblaCarousel from 'embla-carousel-react'
import Autoplay from 'embla-carousel-autoplay'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true }, [Autoplay()])

  const logAutoplayStart = (emblaApi, event) => {
    console.log(`${event.type} fired`)
  }

  useEffect(() => {
    if (!emblaApi) return

    emblaApi.on('autoplay:play', logAutoplayStart)
    emblaApi.plugins().autoplay?.play()
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>
    </div>
  )
}
