// website/src/content/v9/code-snippets/guides/dot-buttons/buttons-state-solid-01.jsx
import { createSignal, createEffect, For } from 'solid-js'
import useEmblaCarousel from 'embla-carousel-solid'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel(() => ({
    loop: false
  }))
  const [scrollSnaps, setScrollSnaps] = createSignal([])
  const [selectedSnap, setSelectedSnap] = createSignal(0)

  const goTo = (index) => emblaApi()?.goTo(index)
  const setupSnaps = (emblaApi) => setScrollSnaps(emblaApi.snapList())
  const setActiveSnap = (emblaApi) => setSelectedSnap(emblaApi.selectedSnap())

  createEffect(
    () => emblaApi(),
    (api) => {
      if (!api) return

      setupSnaps(api)
      setActiveSnap(api)

      api.on('reinit', setupSnaps)
      api.on('reinit', setActiveSnap)
      api.on('select', setActiveSnap)
    }
  )

  return (
    <div class="embla">
      <div class="embla__viewport" ref={emblaRef}>
        <div class="embla__container">
          <div class="embla__slide">Slide 1</div>
          <div class="embla__slide">Slide 2</div>
          <div class="embla__slide">Slide 3</div>
        </div>
      </div>

      <div class="embla__dots">
        <For each={scrollSnaps()}>
          {(_, index) => (
            <button
              class={'embla__dot'.concat(
                index() === selectedSnap() ? ' embla__dot--selected' : ''
              )}
              onClick={() => goTo(index())}
            >
              {/* Button content */}
            </button>
          )}
        </For>
      </div>
    </div>
  )
}

// packages/embla-carousel-docs/src/content/code-snippets/guides/dot-buttons/buttons-state-react-01.jsx
import React, { useState, useEffect } from 'react'
import useEmblaCarousel from 'embla-carousel-react'

export function EmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false })
  const [scrollSnaps, setScrollSnaps] = useState([])
  const [selectedSnap, setSelectedSnap] = useState(0)

  const goTo = (index) => emblaApi?.goTo(index)
  const setupSnaps = (emblaApi) => setScrollSnaps(emblaApi.snapList())
  const setActiveSnap = (emblaApi) => setSelectedSnap(emblaApi.selectedSnap())

  useEffect(() => {
    if (!emblaApi) return

    setupSnaps(emblaApi)
    setActiveSnap(emblaApi)

    emblaApi.on('reinit', setupSnaps)
    emblaApi.on('reinit', setActiveSnap)
    emblaApi.on('select', setActiveSnap)
  }, [emblaApi])

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaRef}>
        <div className="embla__container">
          <div className="embla__slide">Slide 1</div>
          <div className="embla__slide">Slide 2</div>
          <div className="embla__slide">Slide 3</div>
        </div>
      </div>

      <div className="embla__dots">
        {scrollSnaps.map((_, index) => (
          <button
            className={'embla__dot'.concat(
              index === selectedSnap ? ' embla__dot--selected' : ''
            )}
            key={index}
            onClick={() => goTo(index)}
          >
            {/* Button content */}
          </button>
        ))}
      </div>
    </div>
  )
}
