// packages/embla-carousel-docs/src/content/code-snippets/guides/dot-buttons/buttons-state-svelte-01.svelte
<script>
  import useEmblaCarousel from 'embla-carousel-svelte'

  let emblaApi
  let options = { loop: false }
  let scrollSnaps = []
  let selectedSnap = 0

  const scrollToSnap = (index) => emblaApi?.scrollToSnap(index)
  const setupSnaps = (emblaApi) => (scrollSnaps = emblaApi.snapList())
  const setActiveSnap = (emblaApi) => (selectedSnap = emblaApi.selectedSnap())

  function onInit(event) {
    emblaApi = event.detail

    setupSnaps(emblaApi)
    setActiveSnap(emblaApi)

    emblaApi.on('reinit', setupSnaps)
    emblaApi.on('reinit', setActiveSnap)
    emblaApi.on('select', setActiveSnap)
  }
</script>

<div class="embla">
  <div
    class="embla__viewport"
    on:emblainit={onInit}
    use:useEmblaCarousel={{ options }}
  >
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>

  <div class="embla__dots">
    {#each scrollSnaps as _, index}
      <button
        class="embla__dot"
        class:embla__dot--selected={index === selectedSnap}
        on:click={() => scrollToSnap(index)}
      >
        <!-- Button content -->
      </button>
    {/each}
  </div>
</div>

// packages/embla-carousel-docs/src/content/code-snippets/guides/dot-buttons/buttons-state-vue-01.vue
<script setup>
import { ref, watch } from 'vue'
import useEmblaCarousel from 'embla-carousel-vue'

const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false })
const scrollSnaps = ref([])
const selectedSnap = ref(0)

const scrollToSnap = (index) => emblaApi.value?.scrollToSnap(index)
const setupSnaps = (emblaApi) => (scrollSnaps.value = emblaApi.snapList())
const setActiveSnap = (emblaApi) =>
  (selectedSnap.value = emblaApi.selectedSnap())

watch(
  emblaApi,
  (api) => {
    if (!api) return

    setupSnaps(api)
    setActiveSnap(api)

    api.on('reinit', setupSnaps)
    api.on('reinit', setActiveSnap)
    api.on('select', setActiveSnap)
  },
  { immediate: true }
)
</script>

<template>
  <div class="embla">
    <div class="embla__viewport" ref="emblaRef">
      <div class="embla__container">
        <div class="embla__slide">Slide 1</div>
        <div class="embla__slide">Slide 2</div>
        <div class="embla__slide">Slide 3</div>
      </div>
    </div>

    <div class="embla__dots">
      <button
        :class="[
          'embla__dot',
          index === selectedSnap ? 'embla__dot--selected' : ''
        ]"
        :key="index"
        v-for="(_, index) in scrollSnaps"
        @click="scrollToSnap(index)"
      >
        <!-- Button content -->
      </button>
    </div>
  </div>
</template>
